version: 2.1

# Define a reusable executor
executors:
  go_executor:
    docker:
      - image: cimg/go:1.17.0
    working_directory: /go/src/github.com/<your-account>/<your-repo>

jobs:
  build_and_test:
    executor: go_executor
    steps:
      - checkout
      - run: go version
      - run: go mod download
      - run: go build -v ./...
      - run: go test -v ./...

# Define the workflow
workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build_and_test
